### ISSUE TITLE
弱弱问一下，能不能把kindle安卓的固件放出来啊

### ISSUE THREAD

**Issue by kerncoola** [wegank/GoogleCN#1]
正如你所说的“无疑违背了开源精神”一样，放出来打破它！

**Comment by wegank** [comment]
此前的博文被 ISP 告知违反 [DADVSI](https://fr.wikipedia.org/wiki/Loi_relative_au_droit_d%27auteur_et_aux_droits_voisins_dans_la_soci%C3%A9t%C3%A9_de_l%27information)，需要立即删除。抱歉无法进行进一步研究。

**Comment by kerncoola** [comment]
好的
